Repository bl1231/bilbomd-ui, pull requests merged in 2024-12, with the labels that each got.

#772 Upgrade react router
  package-lock.json
  package.json
  src/components/Home.tsx
  src/components/__tests__/Home.test.tsx
  src/features/af2pae/Alphafold2PAEJiffy.tsx
  src/features/alphafoldjob/NewAlphaFoldJobForm.tsx
  src/features/auth/MagickLink.tsx
  src/features/auth/MagickLinkAuth.tsx
  src/features/auth/PersistLogin.tsx
  src/features/auth/Prefetch.tsx
  src/features/auth/RequireAuth.tsx
  src/features/auth/Signup.tsx
  src/features/auth/VerifyEmail.tsx
  src/features/auth/__tests__/MagickLinkAuth.test.tsx
  src/features/autojob/NewAutoJobForm.tsx
  src/features/jobs/JobDetails.tsx
  src/features/jobs/NewJobForm.tsx
  src/features/jobs/SingleJobPage.tsx
  src/features/multimd/NewMultiMDJobForm.tsx
  src/features/sansjob/NewSANSJobForm.tsx
  src/features/scoperjob/NewScoperJobForm.tsx
  src/features/users/EditUser.tsx
  src/features/users/EditUserForm.tsx
  src/features/users/UsersList.tsx
  src/features/users/__tests__/EditUser.test.tsx
  src/layout/MainLayout/Header/index.tsx
  src/layout/MainLayout/index.tsx
  src/layout/MinimalLayout/Header/index.tsx
  src/layout/MinimalLayout/index.tsx
  src/main.tsx
  src/routes/index.ts
  src/test/test-utils.tsx
Labels: dependencies

#785 782 move accordian disclosure arrow
  src/features/af2pae/PAEJiffy.tsx
  src/features/af2pae/PAEJiffyInstructions.tsx
  src/features/autojob/NewAutoJobFormInstructions.tsx
  src/features/jobs/NewJobForm.tsx
  src/themes/overrides/Accordion.ts
Labels: enhancement

#792 can't have <div> inside typography elements
  src/features/multimd/NewMultiMDJobForm.tsx
Labels: bug

#798 793 unit testing continuation after husky configuration
  src/features/af2pae/DownloadAF2PAEfile.tsx
  src/features/af2pae/PAEJiffy.tsx
  src/features/af2pae/__tests__/ConstInpFile.test.tsx
  src/features/af2pae/__tests__/DowloadAF2PAEfile.test.tsx
  src/features/af2pae/__tests__/PAEJiffyInstructions.test.tsx
  src/features/af2pae/__tests__/PAESlider.test.tsx
  src/features/af2pae/__tests__/PlddtSlider.test.tsx
  src/features/alphafoldjob/__tests__/NewAlphaFoldJobForm.test.tsx
  src/features/alphafoldjob/__tests__/NewAlphaFoldJobFormInstructions.test.tsx
  src/features/analysis/__tests__/BilboMdFeedback.test.tsx
  src/features/analysis/__tests__/Feedback.test.tsx
  src/layout/MainLayout/Footer/index.test.tsx
  src/layout/MainLayout/Header/index.test.tsx
  src/layout/MainLayout/index.test.tsx
  src/routes/__tests__/LoginRoutes.test.tsx
  src/routes/__tests__/index.test.tsx
Labels: unit testing

#800 Improve Job MongoDB component `JobDBDetails`
  src/components/CopyableChip.tsx
  src/features/jobs/BilboMDMongoSteps.tsx
  src/features/jobs/JobDBDetails.tsx
  src/features/jobs/SingleJobPage.tsx
  src/features/multimd/MultiMDJobDBDetails.tsx
  src/slices/jobsApiSlice.ts
  src/types/interfaces.ts
Labels: enhancement

#803 set minwidth and flexgrow on nersc steps
  src/features/jobs/SingleJobPage.tsx
Labels: enhancement

#811 Fix sans submit not working
  src/features/sansjob/NewSANSJobForm.tsx
Labels: bug
